### ISSUE TITLE
Chrome's crash while loading history from local

### ISSUE THREAD

**Issue by Lix124** [ALiangLiang/Counter-for-Messenger#1]
While the extension loading history from local, the Chrome crashes after about 3-4 seconds. I tried uninstall the extension and install it again but it didn't help.

**Comment by rontap** [comment]
Try having no other tabs and apps running, i think chrome runs out of space

**Comment by ALiangLiang** [comment]
Maybe no enough memory? But this problem can be soluted.

**Comment by Lix124** [comment]
I closed all other tabs and the problem still occurs

**Comment by ALiangLiang** [comment]
@Lix124 Can I ask your computer's memory capacity?

**Comment by Lix124** [comment]
I've got 7 GB of RAM
