### ISSUE TITLE
原理？

### ISSUE THREAD

**Issue by tigercosmos** [ALiangLiang/Counter-for-Messenger#10]
可以解釋一下取得資料的原理嗎？

**Comment by ALiangLiang** [comment]
可以，其實就只是跟Messenger頁面一樣，直接向FB伺服器請求資料罷了，沒有什麼特別的操作手法。

如果就技術一點詳細來講，就是透過存取Messenger頁面來取得必須的 token，然後之後透過 Messenger 的官方 API (未直接對外開放)，向FB取得我們所需的資料，例如聊天室(Threads)數量、訊息歷史紀錄等，當然這些全都是在各位的瀏覽器上操作，並不會有任何資料存放在你或FB以外的第三方上。

除了訊息紀錄會因為要減少下次載入時間，而暫存在瀏覽器上，所以我想各位不用擔心資料外洩問題，只要保護好自己的裝置，基本上可以甭擔心這點，

**Comment by tigercosmos** [comment]
所以資料是直接去攔截 XHR 來看

**Comment by tigercosmos** [comment]
不過未公開的 API 可能會常常改變 URL，之後維護會滿麻煩的 XD

**Comment by ALiangLiang** [comment]
說是攔截XHR也不太對，應該說是我模擬一般Messenger向伺服器請求的方式，主動向 Messenger 請求資料這樣。

未公開的API這點應該不用太擔心，其實有個[專案](https://github.com/Schmavery/facebook-chat-api)是在做這方面未公開API的串接，因為社群不小，所以一但有變更會在短時間更新，所以只要跟著他們的進度基本上不會有太大的 gap。

**Comment by tigercosmos** [comment]
喔喔 我覺得可以把 facebook-chat-api 放在 README，這就是我想要的資訊 :)
