### ISSUE TITLE
I can't build to chorme extension.Pls help me !

### ISSUE THREAD

**Issue by cloverdoser** [ALiangLiang/Counter-for-Messenger#14]
I can't build to chorme extension.Pls help me !

**Comment by ALiangLiang** [comment]
What is your question? Can you tell me where you stuck?

**Comment by cloverdoser** [comment]
I don’t know.I’m using “npm” to build chorme extension

**Comment by ALiangLiang** [comment]
You can follow [this section](https://github.com/ALiangLiang/Counter-for-Messenger/blob/master/README.md#-development). I suggest you install [yarn](https://yarnpkg.com) first.  And then install dependencies by `yarn`.

**Comment by ALiangLiang** [comment]
OK. And `npm run dev`?

**Comment by cloverdoser** [comment]
Yes.And error

**Comment by ALiangLiang** [comment]
So can you paste your error message?

**Comment by cloverdoser** [comment]
Oh.I don’t have computer now.And I think You can make video tutorial build chorme extension :)))

**Comment by cloverdoser** [comment]
https://imgur.com/a/eb7AkWf This's my error.Can u help me!

**Comment by ALiangLiang** [comment]
use another script `npm run build`

**Comment by cloverdoser** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v9.5.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle counter-for-messenger@0.2.5~prebuild: counter-for-messenger@0.2.5
6 info lifecycle counter-for-messenger@0.2.5~build: counter-for-messenger@0.2.5
7 verbose lifecycle counter-for-messenger@0.2.5~build: unsafe-perm in lifecycle true
8 verbose lifecycle counter-for-messenger@0.2.5~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\haicl\Desktop\Counter-for-Messenger-master\Counter-for-Messenger-master\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\PuTTY\;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin;C:\MinGW\bin;C:\Program Files\nodejs\;C:\Program Files\nodejs;C:\Program Files\MongoDB\Server\3.6\bin;C:\Users\haicl\AppData\Local\Programs\Python\Python36-32;C:\Program Files (x86)\Yarn\bin\;C:\Users\haicl\AppData\Local\Microsoft\WindowsApps;C:\Users\haicl\AppData\Roaming\Composer\vendor\bin;C:\Program Files\Git\usr\bin;C:\MinGW\bin;C:\Users\haicl\AppData\Roaming\npm;C:\Program Files\nodejs;C:\Program Files\MongoDB\Server\3.6\bin;C:\Users\haicl\AppData\Local\Programs\Python\Python36-32;C:\Program Files\Heroku\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\haicl\AppData\Local\Yarn\bin
9 verbose lifecycle counter-for-messenger@0.2.5~build: CWD: C:\Users\haicl\Desktop\Counter-for-Messenger-master\Counter-for-Messenger-master
10 silly lifecycle counter-for-messenger@0.2.5~build: Args: [ '/d /s /c',
10 silly lifecycle   'webpack --config ./core/webpack.prod.js -p --progress --hide-modules --colors --env.CHROME' ]
11 silly lifecycle counter-for-messenger@0.2.5~build: Returned: code: 2  signal: null
12 info lifecycle counter-for-messenger@0.2.5~build: Failed to exec build script
13 verbose stack Error: counter-for-messenger@0.2.5 build: `webpack --config ./core/webpack.prod.js -p --progress --hide-modules --colors --env.CHROME`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid counter-for-messenger@0.2.5
15 verbose cwd C:\Users\haicl\Desktop\Counter-for-Messenger-master\Counter-for-Messenger-master
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v9.5.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error counter-for-messenger@0.2.5 build: `webpack --config ./core/webpack.prod.js -p --progress --hide-modules --colors --env.CHROME`
22 error Exit status 2
23 error Failed at the counter-for-messenger@0.2.5 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by cloverdoser** [comment]
[WCER]: Cannot find module '../core/.env' => what happened ?

**Comment by ALiangLiang** [comment]
You need to create `.env.js` file by `.env.example.js` first

**Comment by cloverdoser** [comment]
where does the file config of dialog "Please be patient" ?

**Comment by lepatrick714** [comment]
Works now! Thanks @ALiangLiang
