### ISSUE TITLE
Language codes

### ISSUE THREAD

**Issue by mariansam** [ALiangLiang/Counter-for-Messenger#21]
There are two directories in `/src/_locales/`, one is `en` and the second is `zh_TW`. According to Contributing guidelines, we should use two letter ISO codes. This doesn't make any sense.

**Comment by ALiangLiang** [comment]
My fault. When I was writing the contributing guidelines, I did not consider the language variant. In fact, if we have variant languages, we should use xx_YY to distinguish between the two languages.

**Comment by ALiangLiang** [comment]
solved in https://github.com/ALiangLiang/Counter-for-Messenger/commit/f4570612efb97c61d8cec797693b3e29f929662c
