### ISSUE TITLE
TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by AbilarshViji** [ALiangLiang/Counter-for-Messenger#3]
From line 360-385 in main.js, you are missing the thread_type "ROOM" and "MARKETPLACE". This is causing the graph to not load, and stay on the spinner.

**Comment by ALiangLiang** [comment]
Really!?  I never noticed these types.  Very thanks for your report. It's really useful.

**Comment by AbilarshViji** [comment]
This seems to have fixed the problem, the extension is loading fine for me now. Thanks!
