### ISSUE TITLE
Some conversations not broken down

### ISSUE THREAD

**Issue by WPaupa** [ALiangLiang/Counter-for-Messenger#4]
In some conversations the number of messages I/my partner sent is not showing, and I see only the total. I think it occurs with the conversations that got into the list after I installed the addon. Reinstalling doesn't fix the issue. The problem is also present in the character list. Mousing over the bar shows the total, and shows the number of messages sent by either side as NaN
![image](https://user-images.githubusercontent.com/10261247/36116842-f7576740-1037-11e8-8363-935571aa86f8.png)

**Comment by ALiangLiang** [comment]
I see. It's not easy to fixed. So plz wait for my next big updating. Maybe it can fixed this problem.
