### ISSUE TITLE
Download messages

### ISSUE THREAD

**Issue by Rantea** [ALiangLiang/Counter-for-Messenger#5]
Download messages not support unicode character

**Comment by garyng** [comment]
Any fixes for this?

**Comment by ALiangLiang** [comment]
fix now. maybe 1~3 days

**Comment by ALiangLiang** [comment]
@Rantea  Can you paste what unicode character not support?

**Comment by garyng** [comment]
@ALiangLiang 简体中文吧？
我这里显示的全是乱码

![image](https://user-images.githubusercontent.com/4453664/36800186-d1e81338-1ce9-11e8-9f64-7f9c49ffb20c.png)

**Comment by Rantea** [comment]
![image](https://user-images.githubusercontent.com/36815908/36855768-f71104ae-1da6-11e8-99d9-97d9c4cb59c6.png)
this is

**Comment by Rantea** [comment]
![image](https://user-images.githubusercontent.com/36815908/36855889-3f26361a-1da7-11e8-9468-dbf546ff3864.png)

and this is other bug, can u fix it?
Maybe it happened while the conversation was too long (39541 messages).

**Comment by kokonguyen191** [comment]
@Rantea the other bug should be emoji, picture, sound messages or file upload.

**Comment by ALiangLiang** [comment]
New beta version is updated. I think it's fixed the unicode problem by separating many messages to multiple page. But still not support pircture, sound messages... I'm work in progress

https://chrome.google.com/webstore/detail/counter-for-messenger/flkejcheidpcclcdokndihmnlejfabil?hl=zh-TW

**Comment by ALiangLiang** [comment]
@Rantea  beta solved?

**Comment by Rantea** [comment]
@ALiangLiang ok, i see fine. And other bug seems to have been overcome. I still think that the error occurred when the message was too long, when it was cut (4 part) in the beta was no longer.
Anyway, thank you!

**Comment by Rantea** [comment]
@kokonguyen191 It is the first message of the conversation. I'm sure it's not.

**Comment by ALiangLiang** [comment]
solved
